# Server
server.port=3000

# SQLite Database
spring.datasource.url=jdbc:sqlite:./mydrive.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# File Upload limits
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Custom config
app.upload-dir=./uploads
app.jwt-secret=MySuperSecretKey2024_ChangeThis_MustBe32CharsLong!
app.jwt-expiration-ms=86400000